name: Maclari Guncelle

on:
  schedule:
    - cron: '*/15 * * * *' # Her 15 dakikada bir otomatik çalışır
  workflow_dispatch: # İstersen elinle de başlatabilirsin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v2

      - name: Python Kur
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: pip install cloudscraper beautifulsoup4

      - name: Botu Çalıştır
        run: python taraftar.py

      - name: Değişiklikleri Kaydet
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add yayinlar.json
          git commit -m "Yayinlar guncellendi" || exit 0
          git push
